//arcaea難易度別曲リスト
var arc7=new Array(
    "inkar-usi",
    "Fairytale",
    "Infinity Heaven",
    "Moonlight of Sand Castle",
    "Blossoms",
    "Dream goes on",
    "vsキミ戦争",
    "Sayonara Hatsukoi",
    "Suomi",
    "Vexaria",
    "Brand new world",
    "クロートーと星の観測者",
    "First Snow",
    "Rise",
    "Dement ~after legend~",
    "Paradise",
)
var arc8=new Array(
    "san skia",
    "Dantalion [PRS]",
    "1F√",
    "Bookmaker (2D Version)",
    "Diode",
    "Dot to Dot feat. shully",
    "Genesis",
    "光",
    "I've heard it said",
    "Relentless",
    "Shades of Light in a Transcendent Realm",
    "Cyaegha [PRS]",
    "Ether Strike [PRS]",
    "Halcyon [PRS]",
    "Live Fast Die Young [PRS]",
    "Ringed Genesis [PRS]",
    "四月の雨",
    "blue comet",
    "enchanted love",
    "Hall of Mirrors",
    "ハルトピア~Utopia of Spring~",
    "Lucifer",
    "九番目の迷路",
    "Oblivia",
    "One Last Drive",
    "Paper Witch",
    "Prism",
    "Quon",
    "Tie me down gently",
    "Vivid Theory",
    "Axium Crisis [PRS]",
    "Overwhelm [PRS]",
    "Antithese",
    "Babaroque",
    "Beside You",
    "Call My Name feat. Yukacco",
    "Chelsea",
    "Dandelion",
    "DDD",
    "Eccentric Tale",
    "INTERNET OVERDOSE",
    "Lights of Muse",
    "Lumia",
    "Purgatorium",
    "REconstruction",
    "Silent Rush",
    "Surrender",
    "world.execute(me);",
    "Ävril -Flicka i krans-",
    "BUCHiGiRE Berserker [PRS]",
    "IZANA [PRS]",
    "業 -善なる神とこの世の悪について- [PRS]",
    "PRAGMATISM [PRS]",
    "烈華RESONANCE [PRS]",
    "Coastal Highway",
    "Cosmica",
    "FREEF4LL",
    "Gekka (Short Version)",
    "Grimheart",
    "Moonheart",
    "next to you",
    "Particle Arts",
    "Rabbit In The Black Room",
    "Reinvent",
    "Senkyou",
    "GENOCIDER [PRS]",
    "cry of viyella",
    "Evoltex (poppi'n mix)",
    "Flashback",
    "Journey",
    "memoryfactory.lzh",
    "Snow White",
    "虚空の夢",
    "MERLIN",
    "Turbocharger",
    "Vexaria [BYD]",
    "Aegleseeker [PRS]",
    "dropdead"
)
var arc9=new Array(    
    "Grievous Lady [PRS]",
    "Empire of Winter",
    "Faint Light (Arcaea Edit)",
    "フライブルクとエンドロウル",
    "Give Me a Nightmare",
    "Iconoclast",
    "Jump",
    "神奈川電脳暗渠",    
    "Life is PIANO",
    "qualia -ideaesthesia-",
    "ReviXy",    
    "#1f1e33 [PRS]",
    "Auxesia",
    "Blaster",
    "Blue Rose",
    "Chronostasis",
    "CROSS†OVER",
    "Essence of Twilight",
    "Lapis",
    "La'qryma of the Wasteland",
    "Libertas",
    "Oracle",    
    "Rugie",
    "Strongholds",
    "Syro",    
    "Teriqma",
    "Fracture Ray [PRS]",
    "最強STRONGER [PRS]",
    "AI[UE]OON",
    "Alice à la mode",
    "Alice's Suitcase",
    "Blocked Library",
    "ベースラインやってる？w",
    "Crystal Gravity",
    "ネコノテ・カリタガール",
    "Equilibrium",    
    "Feels So Right feat. Renko",
    "GOODTEK (Arcaea Edit)",
    "lastendconductor",    
    "Let you DIVE! (nitro rmx)",
    "Lost Civilization",
    "NULCTRL",
    "Party Vinyl",
    "ピコPico*とらんすれーしょんっ！",
    "Phantasia",
    "Small Cloud Sugar Candy",
    "STAGER (ALL STAGE CLEAR)",
    "Vindication",
    "ΟΔΥΣΣΕΙΑ",
    "MERLIN [BYD]",    
    "Tempestissimo [PRS]",
    "Anökumene",
    "Astral tale",    
    "Be There",
    "CROSS†SOUL",
    "Dreamin' Attraction!!",
    "緋纏いの宵",
    "Fallensquare",
    "狂言綺語",
    "Glow",
    "Ignotus",
    "堕楽の園",
    "Red and Blue",
    "Sakura Fubuki",    
    "Specta",
    "VECTOЯ",
    "夜桜吹雪",    
    "Your voice so... feat. Such",
    "Lumia [BYD]",
    "next to you [BYD]",
    "Purgatorium [BYD]",
    "amygdata",
    "Avant Raze",
    "scythe",
    "Cybernecia Catharsis",
    "DataErr0r",
    "Final Step!",
    "Head BONK ache",    
    "不浄な白い鳥",
    "Lazy Addiction",
    "白道、多希望羊と信じありく。",    
    "MAHOROBA",
    "Monochrome Princess",
    "OMAKENO Stroke",
    "with U",
    "Antithese [BYD]",
    "Fairytale [BYD]",
    "dropdead [PRS]",
    "ENERGY SYNERGY MATRIX",
    "Purple Verse",
    "Infinity Heaven [BYD]"
)
var arc9p=new Array(    
    "μ",
    "迷える音色は恋の唄",
    "BLRINK",
    "Got hive of Ra",
    "Heart Jackin'",
    "Lethaeus",
    "Memory Forest",
    "Quon",
    "SUPERNOVA",    
    "BATTLE NO.1",
    "Dreadnought",
    "秋の陽炎",    
    "Heavenly caress",
    "Heavensdoor",
    "Linear Accelerator",
    "nέο κόsmo",
    "Sulfur",
    "彩る夏の恋花火",
    "The Message",
    "7thSense",
    "Altale",
    "AlterAle",
    "Arcahv",    
    "Ascent",
    "Corruption",
    "Dazzle hop",    
    "DX超性能フルメタル少女",
    "goldenslaughterer",
    "init()",
    "Lost Desire",
    "Protoflicker",
    "SOUNDWiTCH",
    "Vandalism",
    "qualia -ideaesthesia- [BYD]",
    "Antagonism",
    "BADTEK",
    "竹",    
    "Black Territory",
    "Far Away Light",
    "Galaxy Friends",    
    "Mazy Metroplex",
    "Nhelv",
    "Scarlet Cage",
    "THE ULTIMACY",
    "Xeraphinite",
    "Dement ~after legend~ [BYD]",
    "Ignotus Afterburn [BYD]",
    "La'qryma of the Wasteland [BYD]",
    "Black Lotus",
    "Einherjar Joker",
    "Filament",    
    "GOODTEK (Arcaea Edit)[BYD]",
    "Macrocosmic Modulation",
    "神奈川電脳暗渠 [BYD]",    
    "Lost Civilization [BYD]",
    "Moonheart [BYD]"
)
var arc10=new Array(    
    "HIVEMIND",
    "Alexandrite",
    "Mirzam",
    "Modelista",
    "Scarlet Lance",
    "妖艶魔女 -trappola bewitching-",
    "Vicious Heroism",
    "Xanatos",
    "conflict",    
    "Ether Strike",
    "Malicious Mischance",
    "Metallic Punisher",    
    "Oshama Scramble!",
    "PRAGMATISM",
    "Redolent Shape",
    "Sheriruth",
    "Viyella's Tears",
    "lastendconductor [BYD]",
    "Garakuta Doll Play",
    "Last Celebration",
    "Medusa",
    "NEO WINGS",
    "Nirv lucE",    
    "Tiferet",
    "Valhalla:0",
    "αterlβus",    
    "Bookmaker (2D Version) [BYD]",
    "overdead. [BYD]",
    "Aurgelmir",
    "Climax",
    "cyanine",
    "Felis",
    "G e n g a o z o",
    "GIMME DA BLOOD",
    "GLORY：ROAD",
    "怒槌",
    "Löschen",    
    "γuarδina",
    "Quon [BYD]",
    "Red and Blue and Green [BYD]",    
    "Singularity VVVIP [BYD]",
    "AttraqtiA",
    "corps-sans-organes",
    "IZANA",
    "Kissing Lucifer",
    "Lightning Screw",
    "Live Fast Die Young",
    "Overwhelm",
    "Seclusion",
    "Sheriruth (Laur Remix)",
    "アリス・リデルに捧ぐ",    
    "OMAKENO Stroke [BYD]",
    "Tempestissimo"
)
var arc10p=new Array(    
    "ouroboros -twin stroke of the end-",
    "烈華RESONANCE",
    "Ringed Genesis",
    "Singularity",
    "AMAZING MIGHTYYYY!!!!",
    "Axium Crisis",
    "BUCHiGiRE Berserker",
    "Cyaegha",
    "光速神授説 - Divine Light of Myriad -",    
    "GENOCIDER",
    "Halcyon",
    "Stasis",    
    "World Vanquisher",
    "Heavensdoor [BYD]",
    "Dantalion",
    "業 -善なる神とこの世の悪について-",
    "ω4",
    "#1f1e33"
)
var arc11=new Array(    
    "Fracture Ray",
    "Grievous Lady",
    "Aegleseeker",
    "最強STRONGER",
    "PRAGMATISM -RESURRECTION- [BYD]",
    "Tempestissimo [BYD]"
)
